<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.techsenger.maven.root</groupId>
        <artifactId>maven-root</artifactId>
        <version>1.6.0-SNAPSHOT</version>
    </parent>

    <groupId>com.techsenger.jeditermfx</groupId>
    <artifactId>jeditermfx</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>JediTermFX</name>
    <description>Terminal emulator for JavaFX</description>

    <licenses>
        <license>
            <name>Apache 2.0 License</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
        <license>
            <name>LGPLv3</name>
            <url>https://www.gnu.org/licenses/lgpl-3.0.en.html</url>
        </license>
    </licenses>

    <url>https://github.com/techsenger/jeditermfx</url>

    <scm>
        <connection>scm:git:https://github.com/techsenger/jeditermfx.git</connection>
        <developerConnection>scm:git:https://github.com/techsenger/jeditermfx.git</developerConnection>
        <url>https://github.com/techsenger/jeditermfx</url>
    </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/techsenger/jeditermfx/issues</url>
    </issueManagement>

    <developers>
        <developer>
            <id>pcastornii</id>
            <name>Pavel Castornii</name>
        </developer>
    </developers>

    <properties>
        <checkstyle.plugin.skip>true</checkstyle.plugin.skip>
        <!-- dependencies -->
        <jna.version>5.17.0</jna.version>
        <purejavacomm.version>0.0.11.1</purejavacomm.version>
        <annotations.version>24.0.1</annotations.version>
        <pty4j.version>0.12.25</pty4j.version>
        <javafx.version>19.0.2.1</javafx.version>
        <publishing.plugin.exclusions>jeditermfx-app</publishing.plugin.exclusions>
    </properties>

    <repositories>
        <repository>
            <id>JetBrains</id>
            <url>https://packages.jetbrains.team/maven/p/ij/intellij-dependencies</url>
        </repository>
        <repository>
            <id>repsy-snapshots</id>
            <url>https://repo.repsy.io/mvn/techsenger/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.techsenger.osp.bom</groupId>
                <artifactId>osp-bom</artifactId>
                <version>1.7.0-SNAPSHOT</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <!--### JediTermFX ###-->
            <dependency>
                <groupId>com.techsenger.jeditermfx</groupId>
                <artifactId>jeditermfx-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.techsenger.jeditermfx</groupId>
                <artifactId>jeditermfx-ui</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!--### JavaFX ###-->
            <dependency>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-controls</artifactId>
                <version>${javafx.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-base</artifactId>
                <version>${javafx.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-graphics</artifactId>
                <version>${javafx.version}</version>
            </dependency>

            <!--### JetBrains ###-->
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>${annotations.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.pty4j</groupId>
                <artifactId>pty4j</artifactId>
                <version>${pty4j.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.pty4j</groupId>
                <artifactId>purejavacomm</artifactId>
                <version>${purejavacomm.version}</version>
                <scope>compile</scope>
            </dependency>

            <!--### JNA ###-->
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna</artifactId>
                <version>${jna.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna-platform</artifactId>
                <version>${jna.version}</version>
                <scope>runtime</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>jeditermfx-core</module>
        <module>jeditermfx-ui</module>
        <module>jeditermfx-app</module>
    </modules>
</project>



